version: '3.6'
services:
  web:
    image: gkulasik/grpc_assistant_server:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - /Users:/app/Users
    environment:
      RAILS_ENV: development