module BuilderMetadata
  IMPORT_PATH = "IMPORT_PATH".to_sym
  SERVICE_PROTO_PATH = "SERVICE_PROTO_PATH".to_sym
  PLAINTEXT = "PLAINTEXT".to_sym
  VERBOSE = "VERBOSE".to_sym
  SERVER_ADDRESS = "SERVER_ADDRESS".to_sym
  ASSISTANT_OPTIONS = "GAS_OPTIONS".to_sym
  MAX_MESSAGE_SIZE = "MAX_MESSAGE_SIZE".to_sym
  MAX_TIME = "MAX_TIME".to_sym
  CONNECT_TIMEOUT = "CONNECT_TIMEOUT".to_sym
end